# Setup
title: Poole
tagline: Poole
url: https://jasaindigo.art.blog
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-61724925-5

# Specify the author for blog posts
author:
  name: Poole
  url: https://123nousirons.blogspot.com
  email: markdotto@gmail.com

# Custom vars
version: 3.0.0
